### ISSUE TITLE
failed and stuck when createTaskSmee Task

### ISSUE THREAD

**Issue by lzyun** [ad-m/python-anticaptcha#50]
`
task = NoCaptchaTaskProxylessTask(website_url=url,
        website_key=site_key
)
try:
        print ('create task')
        job = client.createTaskSmee(task)
        print ('join...')
        job.join()
        print ('wait response!!')
        g_response = job.get_solution_response()
except:
        print (traceback.print_exc())`

Often stuck at 'client.createTaskSmee(task)', does anyone have same experience?

**Comment by ad-m** [comment]
Thank you for the information about issues in ```createTaskSmee```.

Can you provide task IDs where the result was not received? Then you will be able to contact Anti-captcha.com technical support that their request has been correctly delivered to Smee.io. 

How often do you get this problem (percentage of requests)? 

I do not note such problems, but ```createTaskSmee``` uses the free smee.io service, which does not guarantee any level of SLA. Can you use ```createTask``` (using callback or through polling)? I'd like to help you improve your code. If we confirm that the problem is Smee.io, I can consider launching my own service of this kind & hope to provide better level of operation.

**Comment by ad-m** [comment]
Added support for timeout of Smee. See release note for version ```0.6.0```. Upgrade, please.
