### ISSUE TITLE
ERROR_INCORRECT_SESSION_DATA even though its correct!

### ISSUE THREAD

**Issue by BarryThrill** [ad-m/python-anticaptcha#9]
Hello mate!

I have been trying to copy paste the code that you have made 

```
from python_anticaptcha import AnticaptchaClient, NoCaptchaTaskProxylessTask

api_key = '' <--- My own API
site_key = '6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-'  # grab from site
url = 'https://www.google.com/recaptcha/api2/demo'

client = AnticaptchaClient(api_key)
task = NoCaptchaTaskProxylessTask(url, site_key)
job = client.createTask(task)
job.join()
print job.get_solution_response()
```

However whenever site I try if its google, test page or whatever site that has Captcha (With the correct site key aswell) it gives you a error of : 
`
python_anticaptcha.exceptions.AnticatpchaException: [ERROR_INCORRECT_SESSION_DATA:24]Some of the required values for successive user emulation are missing.. Website stoken is invalid. Expected string value, received array`

I tried to change API, tried to change site, even tried other anti-services such as 2cap and dbd and worked fine. I assume there might be a issue when it comes to^

`job = client.createTask(task)`^

I tried to print anything before that code and after and it gets error on that row code.

Maybe its something you can look it up?

Sorry for my bad english btw, Hopefully its not only me!

```
`
    client = AnticaptchaClient(anticapAPI)
    task = NoCaptchaTaskProxylessTask(URL, Key_Found)
    log("Test")
    job = client.createTask(task)
    log("Test2")
    job.join()
    # print(anti_token)
    anti_token = job.get_solution_response()

    print(anti_token)
`
```

I even tried your own example and it gives the same error!

**Comment by ad-m** [comment]
@BarryThrill , Are you sure you are using the current version of the library? What version of the library does he use? Use ```pip install python-anticaptcha -U````. This message reminds me of an error message that [was removed](https://github.com/ad-m/python-anticaptcha/issues/4) a few months ago. Since then I have introduced automatic verification of the code that has been working correctly recently. I have forced a new test now and [it working](https://travis-ci.org/ad-m/python-anticaptcha/builds/327348408).

**Comment by ad-m** [comment]
@BarryThrill , Are you sure you are using the current version of the library? What version of the library does he use? This message reminds me of an error message that was removed a few months ago.

**Comment by BarryThrill** [comment]
Alright! I will try it now! Apologies for all harm! But will try it now and see!

**Comment by BarryThrill** [comment]
Oh wow. I reinstalled and seems like it was the fix. Looks like it working well now! Once again. Apologies for everything and hopefully this maybe help someone else in the future! 💯

**Comment by ad-m** [comment]
No problem. If you need help - I will be happy to help you. If you had a problem with integration with a specific service - I will be happy to help you too. It receives commissions for every query, so the more library users the better for me. That's why I try to answer as soon as possible. I apologize for the quite long (after all) response time.
